src/DealsBundle/Entity/Deal.php
<?php

namespace DealsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Deal
 *
 * @ORM\Table(name="deal")
 * @ORM\Entity(repositoryClass="DealsBundle\Repository\DealRepository")
 */
class Deal
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="titre", type="string", length=155)
     */
    private $titre;

    /**
     * @var float
     *
     * @ORM\Column(name="prixOrigine", type="float")
     */
    private $prixOrigine;

    /**
     * @var float
     *
     * @ORM\Column(name="prixPromo", type="float")
     */
    private $prixPromo;

    /**
     * @var string
     *
     * @ORM\Column(name="Description", type="text", nullable=true)
     */
    private $description;

    /**
     * @var float
     *
     * @ORM\Column(name="livraison", type="float")
     */
    private $livraison;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datePublication", type="datetime")
     */
    private $datePublication;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateExpiration", type="datetime")
     */
    private $dateExpiration;

    /**
     * @var string
     *
     * @ORM\Column(name="localisation", type="string", length=255)
     */
    private $localisation;

    //    /**
    //     * @var boolean
    //     *
    //     * @ORM\Column(name="isNational", type="boolean")
    //     */
    //    private $isNational;

    /**
     * @var int
     *
     * @ORM\Column(name="counter", type="integer", nullable=true)
     */
    private $counter;

    /**
     * @var string
     * @ORM\Column(name="image", type="string")
     * @Assert\NotBlank(message="add img jpg")
     * @Assert\File(mimeTypes={"image/jpeg"})
     */
    private $image;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateDebut", type="datetime")
     */
    private $dateDebut;

    /**
     * @var Categorie
     * @ORM\ManyToOne (targetEntity="Categorie", inversedBy="deals")
     * @ORM\JoinColumn(nullable=false, name="categorie_id", referencedColumnName="id")
     */
    private $categorie;

    /**
     * @ORM\ManyToOne (targetEntity="User", inversedBy="deals")
     * @ORM\JoinColumn(nullable=false, name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="DealVote", mappedBy="deal",cascade="remove")
     */
    private $votes;

    /**
     * Deal constructor
     */
    public function __construct(){
        return $this->datePublication= new \DateTime('now');
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set titre
     *
     * @param string $titre
     *
     * @return Deal
     */
    public function setTitre($titre)
    {
        $this->titre = $titre;

        return $this;
    }

    /**
     * Get titre
     *
     * @return string
     */
    public function getTitre()
    {
        return $this->titre;
    }

    /**
     * Set prixOrigine
     *
     * @param float $prixOrigine
     *
     * @return Deal
     */
    public function setPrixOrigine($prixOrigine)
    {
        $this->prixOrigine = $prixOrigine;

        return $this;
    }

    /**
     * Get prixOrigine
     *
     * @return float
     */
    public function getPrixOrigine()
    {
        return $this->prixOrigine;
    }

    /**
     * Set prixPromo
     *
     * @param float $prixPromo
     *
     * @return Deal
     */
    public function setPrixPromo($prixPromo)
    {
        $this->prixPromo = $prixPromo;

        return $this;
    }

    /**
     * Get prixPromo
     *
     * @return float
     */
    public function getPrixPromo()
    {
        return $this->prixPromo;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Deal
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set livraison
     *
     * @param float $livraison
     *
     * @return Deal
     */
    public function setLivraison($livraison)
    {
        $this->livraison = $livraison;

        return $this;
    }

    /**
     * Get livraison
     *
     * @return float
     */
    public function getLivraison()
    {
        return $this->livraison;
    }

    /**
     * Set datePublication
     *
     * @param \DateTime $datePublication
     *
     * @return Deal
     */
    public function setDatePublication($datePublication)
    {
        $this->datePublication = $datePublication;

        return $this;
    }

    /**
     * Get datePublication
     *
     * @return \DateTime
     */
    public function getDatePublication()
    {
        return $this->datePublication;
    }

    /**
     * Set dateExpiration
     *
     * @param \DateTime $dateExpiration
     *
     * @return Deal
     */
    public function setDateExpiration($dateExpiration)
    {
        $this->dateExpiration = $dateExpiration;

        return $this;
    }

    /**
     * Get dateExpiration
     *
     * @return \DateTime
     */
    public function getDateExpiration()
    {
        return $this->dateExpiration;
    }

    /**
     * Set localisation
     *
     * @param string $localisation
     *
     * @return Deal
     */
    public function setLocalisation($localisation)
    {
        $this->localisation = $localisation;

        return $this;
    }

    /**
     * Get localisation
     *
     * @return string
     */
    public function getLocalisation()
    {
        return $this->localisation;
    }

    /**
     * Set categorie
     *
     * @param \DealsBundle\Entity\Categorie|object $categorie
     * @return Deal
     */
    public function setCategorie(\DealsBundle\Entity\Categorie $categorie)
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * Get categorie
     *
     * @return \DealsBundle\Entity\Categorie
     */
    public function getCategorie()
    {
        return $this->categorie;
    }

    /**
     * Set user
     *
     * @param User|object $user
     *
     * @return Deal
     */
    public function setUser(User $user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getVotes()
    {
        return $this->votes;
    }

// Creation de cette fonction car il y differents votes a  ajouter sinon il y a une erreur (converting String)
    //à check
    /**
     * @return mixed
     */
    public function getSumVotes()
    {
        $sum = 0;
        /** @var DealVote $dealVote */
        foreach ($this->votes as $dealVote){
            $sum += $dealVote->getCounter();
        }
        return $sum;
    }

    public function addVote(){

    }

    /**
     * @param mixed $votes
     */
    public function setVotes($votes)
    {
        $this->votes = $votes;
    }

    /**
     * Get user
     *
     * @return \DealsBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Deal
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set dateDebut
     *
     * @param string $dateDebut
     *
     * @return Deal
     */
    public function setDateDebut($dateDebut)
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    /**
     * Get dateDebut
     *
     * @return string
     */
    public function getDateDebut()
    {
        return $this->dateDebut;
    }


    /**
     * Set image
     *
     * @param string $image
     *
     * @return Deal
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @return boolean
     */
    public function isNational()
    {
        return $this->isNational;
    }

    /**
     * @param bool $isNational
     */
    public function setIsNational($isNational)
    {
        $this->isNational = $isNational;
    }

    /**
     * @return int
     */
    public function getCounter()
    {
        return $this->counter;
    }

    /**
     * @param int $counter
     */
    public function setCounter($counter)
    {
        $this->counter = $counter;
    }

}

src/DealsBundle/Resources/views/Default/addForm.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% for msg in app.session.flashBag.get('error') %}
        <div class="alert alert-danger" role="alert">
            {{ msg }}
        </div>
    {% endfor %}
    <div class="addForm-bg d-flex justify-content-center py-5">
        <div class="card addFormContainer">
            <div class="card-body">
                <h2 class="card-title my-2">{{ 'addForm.h2' |trans }}</h2>
                {{ form_start(form) }}
                <div class="form p-2">
                    <div class="form-group mb-2 border-bottom">
                        {{ form_row(form.url) }}
                        <p>
                            {{ 'addForm.p.link.explication' |trans }}
                        </p>
                        {{ form_errors(form.url) }}
                    </div>
                    <div class="mb--2 border-bottom">
                        <h2>Description</h2>
                        <div class="d-flex flex-row justify-content-between">
                            {{ form_row(form.prixPromo) }}
                            {{ form_row(form.prixOrigine) }}
                        </div>
                        {{ form_row(form.livraison) }}
                    </div>
                    <div>
                        {{ form_row(form.titre) }}
                        {{ form_row(form.description) }}
                        {{ form_row(form.image) }}
                        {{ form_row(form.categorie) }}
                    </div>
                    <div class="jumbotron m-2">
                        {{ form_row(form.dateDebut) }}
                        {{ form_row(form.dateExpiration) }}
                        {{ form_row(form.localisation) }}
{#                        {{ form_row(form.isNational) }}#}
                    </div>
                    {{ form_row(form.submit) }}
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">

    </script>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>

    </style>
{% endblock %}

src/DealsBundle/Resources/views/Default/dealDetail.html.twig
    <div class="container mx-2">
        <div class="d-flex justify-content-center row">
            {% set dateNow = "now"|date('d-m-Y') %}
            {% set dateExpiration = deal.dateExpiration|date('d-m-Y') %}
            {% set difference = date(dateNow).diff(date(dateExpiration)) %}
            {% set leftDays = difference.days %}
            <div class="col-md-12 mb-2" >
                <div class="mb-3"> <img src="{{ deal.image }}" alt="deal image" width="90%" height="95%"> </div>
                <div class="row p-2 bg-white border rounded mb-2">
                    <div class="col-md-12 mt-1">
                        <div class="d-flex flex-column">
                            <div class="mr-2"><i class="fas fa-street-view mr-2"></i>Spot : {{ deal.localisation }}</div>
                            <span class="d-flex justify-content-end">{{ 'categorie.libelle' |trans }}: {{ deal.categorie.nom }}</span>
                        </div>
                        <h5 class="mb-4">{{ deal.titre }}</h5>
                        <div class="d-flex flex-row justify-content-between card-footer mt-3">
                            <small><i class="fas fa-user-circle lr-3 text-muted mr-2"></i>{{ deal.user.username }}</small>
                        </div>
                        <div class="align-items-center align-content-center mt-1">
                            <div class="d-flex flex-row align-items-center">
                                <h4 class="mr-1">{{ deal.prixPromo }} €</h4><s class="strike-text">{{ deal.prixOrigine }} €</s>
                            </div>
                            <h6 class="text-success"><i class="fas fa-truck mr-2"></i> {{ deal.livraison }}€</h6>
                            <div class="d-flex flex-column mt-4">
                                <a class="btn btn-outline-primary btn-sm mt-2 " href="{{  deal.url }}">{{ 'global.show.deal.url' |trans }}<i class="fas fa-bullseye ml-2"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex flex-column card-footer mt-3">
            <small class="text-muted"><i class="fas fa-calendar-minus mr-2 "></i>{{ 'global.upload.date' |trans }} {{ deal.datePublication | date('d-m-Y')}}</small>
            <div class="mr-2 text-danger"><i class="fas fa-hourglass-half mr-2"></i> {{ 'global.expired' |trans }}  {{ deal.dateExpiration | date('d-m-Y')}} dans {{ leftDays }} jours</div>
        </div>
        <div class="my-5">
            <h3 class="border-bottom">Description :</h3>
            <p class="pt-3">{{ deal.description }}</p>
        </div>
    </div>

src/DealsBundle/Resources/views/Default/dealsList.html.twig
{% for deal in deals %}

    {% set dateNow = "now"|date('d-m-Y') %}
    {% set dateExpiration = deal.dateExpiration|date('d-m-Y') %}
    {% set difference = date(dateNow).diff(date(dateExpiration)) %}
    {% set leftDays = difference.days %}
    <div class="col-md-10 mb-2 deal {% if difference.invert == 1 %} disabledEl{% endif %}" data-position="{{ position }}" data-id_deal="{{ deal.id }}">
        <div class="row p-2 bg-white border bg-color rounded mb-2">
            <div class="img-fluid-container col-md-3 mt-1">
                <img class="img-fluid img-responsive rounded product-image" alt="deal image" src="{{ deal.image }}"></div>
            <div class="col-md-6 mt-1 p-2">
                {% if difference.invert == 0 %}
                    <div class="counter d-flex flex-row mb-3{% if app.user %}{% if userService.hasBeenVoted(app.user, deal) %} disabledButton{% endif %}{% endif %}">
                        <button class="btn increment down" id="minus"><i class="fas fa-minus text-primary"></i></button>
                        <strong><span class="count {% if deal.sumVotes > 0 %} text-danger {% endif %}{% if deal.sumVotes < 0 %} text-primary {% endif %}">{{ deal.sumVotes }}</span></strong>
                        <button class="btn increment up" id="plus"><i class="fas fa-plus text-danger"></i></button>
                    </div>
                {% endif %}
                <div class="header-deal d-flex flex-column">
                    {% if difference.invert == 1 %}
                        <div class="mr-2 text-danger"><s><i class="fas fa-hourglass-half mr-2"></i> {{ 'global.expired' |trans }} {{ deal.dateExpiration | date('d-m-Y')}} </s></div>
                    {% elseif leftDays > 0 and  leftDays <= 3 %}
                        <div class="d-flex justify-content-between">
                            <div class="mr-2 text-danger"><i class="fas fa-hourglass-half mr-2"></i> {{ 'global.expireIn' |trans }} {{ deal.dateExpiration | date('d-m-Y')}} (dans {{ leftDays }} jours)</div>
                            <i class="fas fa-fire mr-2 text-danger hot"></i>
                        </div>
                    {% elseif leftDays == 0 %}
                        <div class="d-flex justify-content-between">
                            <div class="mr-2 text-danger"><i class="fas fa-hourglass-half mr-2"></i> {{ 'global.expired' |trans }} {{ deal.dateExpiration | date('d-m-Y')}} (aujourd'hui)</div>
                            <i class="fas fa-fire mr-2 text-danger hot"></i>
                        </div>
                    {% else %}
                        <div class="mr-2"><i class="fas fa-hourglass-half mr-2"></i> {{ 'global.expireIn' |trans }} {{ deal.dateExpiration | date('d-m-Y')}} (dans {{ leftDays }} jours)</div>
                    {% endif %}
                    <div class="mr-2"><i class="fas fa-street-view mr-2"></i><span class="underline">Spot</span> :  {{ deal.localisation }}</div>
                    <span class="d-flex justify-content-end"><span class="underline">{{ 'categorie.libelle' |trans }} </span> :  {{ deal.categorie.nom }}</span>
                </div>
                <h5 class="mb-5">{{ deal.titre }}</h5>
                <div class="d-flex flex-row justify-content-between card-footer mt-3">
                    <small data-id="{{deal.id}}"  data-toggle="popover" title="{{ deal.user.username }}" data-bs-content="Email: {{ deal.user.email }}"><i class="fas fa-user-circle lr-3 text-muted mr-2"></i>{{ deal.user.username }}</small>
                    <small class="text-muted"><i class="fas fa-calendar-minus mr-2 "></i>{{ 'global.upload.date' |trans }} {{ deal.datePublication | date('d-m-Y')}}</small>
                </div>
            </div>
            <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                <div class="price d-flex flex-row align-items-center">
                    <h4 class="mr-1">{{ deal.prixPromo }} €</h4><s class="strike-text">{{ deal.prixOrigine }} €</s>
                </div>
                <h6 class="text-success"><i class="fas fa-truck mr-2"></i> {{ deal.livraison }}€</h6>
                <div class="d-flex flex-column mt-4">
                    <button type="button" class="modalCall btn btn-primary" data-bs-toggle="modal" data-id="{{deal.id}}" data-bs-target="#containDeal">{{ 'global.show.modal' |trans }}<i class="fas fa-info-circle ml-2"></i></button>
                    <button class="btn btn-outline-primary btn-sm mt-2 " href="{{ deal.url }}">{{ 'global.show.deal.url' |trans }}<i class="fas fa-bullseye ml-2"></i></button>
                </div>
            </div>
        </div>
    </div>
    {% set position = position + 1 %}
{% endfor %}

src/DealsBundle/Resources/views/Default/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form_start(form) }}
    <nav class="navbar navbar-light bg-dark d-flex justify-content-center">
{#        Exemple utilisation de service avec les catégories#}
{#        {% set categories = categorieService.getCategories() %}#}
        <div class="search-container d-flex flex-row justify-content-center row pt-2">
            <div class="col-sm">{{ form_row(form.categorie) }}</div>
            <div class="col-sm"> {{ form_row(form.q) }}</div>
            <div class="button col-sm">{{ form_row(form.submit) }}</div>
        </div>
    </nav>
    {{ form_end(form) }}
    {% for msg in app.session.flashBag.get('success') %}
        <div class="alert alert-success" role="alert">
            {{ msg }}
        </div>
    {% endfor %}
    {% for msg in app.session.flashBag.get('error') %}
        <div class="alert alert-danger" role="alert">
            {{ msg }}
        </div>
    {% endfor %}
    <div id="error"></div>
    <div class="main mt-5 mb-5">
        <div class="dealsContainer d-flex justify-content-center row" id="Deals" data-type_search="{{ typeSearch }}">
            {% if deals %}
                {% include "DealsBundle:Default:dealsList.html.twig" with {position: 0} %}
            {% else %}
                <div class="text-center" id="stopScrollNoResults">
                    <h3>Oupss !!</h3>
                    <img class="noResults" alt="noResults" src="/images/noResults.jpg">
                </div>
            {% endif %}

        </div>
        <div class="d-none text-center" id="stopScrollNbDeals">
            <img class="noResults" alt="noResults" src="/images/noResults.jpg">
        </div>
        {# <div class="navigation d-flex justify-content-center mt-4">#}
        {# {{ knp_pagination_render(deals) }}#}
        {# </div>#}
    </div>
    <div class="modal fade" id="containDeal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{{ 'global.show.modal' |trans }}</h5>
{#                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>#}
                    <button type="button" class="close"  data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                   <img id="Loading" src="/images/loading.gif" alt="loading gif">
                    <div id="Content"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-color" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <div id="loader" class="spinner-grow text-danger d-none" role="status">
        <img src="/images/loading.gif" alt="loading gif">
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="/js/index-jquery.js"></script>

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        img{
            width: 100%;
            height:auto!important;
        }

    </style>
{% endblock %}

src/DealsBundle/Resources/views/Default/profile.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% for msg in app.session.flashBag.get('success') %}
        <div class="alert alert-success text-center" role="alert">
            {{ msg }}
        </div>
    {% endfor %}
    {% for msg in app.session.flashBag.get('error') %}
        <div class="alert alert-danger text-center" role="alert">
            {{ msg }}
        </div>
    {% endfor %}
    <div class="bg-img-profil">
        <div class="page-content page-container my-5" id="page-content">
            <div class="pt-2">
                <div class="row container d-flex m-auto">
                    <div class="col-md-12 opacity">
                        <div class="card user-card-full">
                            <div class="row m-0">
                                <div class="col-sm-4 bg-c-lite-green">
                                    <div class="card-block text-center text-white">
                                        <div class="mb-1"> <img src="https://img.icons8.com/bubbles/100/000000/user.png" class="img-radius" alt="User-Profile-Image"> </div>
                                        <h6 class="f-w-600">Pseudo : </h6>
                                        <p>{{ app.user.username }}</p> <i class=" mdi mdi-square-edit-outline feather icon-edit mt-3 f-16"></i>
                                    </div>
                                </div>
                                <div class="col-sm-8 bg-opacity">
                                    <div class="card-block">
                                        <h6 class="mb-4 pb-1 b-b-default f-w-600">Informations</h6>
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <p class="mb-2 f-w-600">Email</p>
                                                <h6 class="text-muted f-w-400">{{ app.user.email }}</h6>
                                            </div>
                                        </div>
                                        <h6 class="mb-4 mt-5 pb-1 b-b-default f-w-600">{{ 'profil.card.h6' |trans }}</h6>
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <p class="mb-2 f-w-600">{{ 'profil.deals.lenght' |trans }}</p>
                                                <h6 class="text-muted f-w-400">{{ deals | length }}</h6>
                                            </div>
                                        </div>
                                        <ul class="social-link list-unstyled mt-5 mb-1">
                                            <li><a href="" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="facebook" data-abc="true"><i class="mdi mdi-facebook feather icon-facebook facebook" aria-hidden="true"></i></a></li>
                                            <li><a href="" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="twitter" data-abc="true"><i class="mdi mdi-twitter feather icon-twitter twitter" aria-hidden="true"></i></a></li>
                                            <li><a href="" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="instagram" data-abc="true"><i class="mdi mdi-instagram feather icon-instagram instagram" aria-hidden="true"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="main">
            <h2 class="text-center border-bottom">{{ 'profil.h2.management' |trans }}</h2>
            <div class="btn-group d-flex justify-content-center my-4" role="group" aria-label="Basic outlined example" id="FiltersDeals">
                <button type="button" class="btn btn-outline-dark" data-type="tous">{{ 'profil.all.btn' |trans }}</button>
                <button type="button" class="btn btn-outline-primary" data-type="en_cours">{{ 'profil.active.btn' |trans }}</button>
                <button type="button" class="btn btn-outline-danger" data-type="expire">{{ 'profil.expired.btn' |trans }}</button>
            </div>
            <div class="d-flex justify-content-center row">
                {% for deal in deals %}
                    {% set dateNow = "now"|date('d-m-Y') %}
                    {% set dateExpiration = deal.dateExpiration|date('d-m-Y') %}
                    {% set difference = date(dateNow).diff(date(dateExpiration)) %}
                    {% set leftDays = difference.days %}
                    <div class="col-md-11 mb-2 deal {% if difference.invert == 1 %}expired disabledEl{% endif %}">
                        <div class="row p-2 bg-white border rounded mb-2">
                            <div class="col-md-3 mt-1"><img class="img-fluid img-responsive rounded product-image" alt="deal-image" src="{{ deal.image}}"></div>
                            <div class="col-md-6 mt-1">
                                <div class="header-deal d-flex flex-column">
                                    {% if difference.invert == 1 %}
                                        <div class="mr-2 text-danger"><s><i class="fas fa-hourglass-half mr-2"></i>{{ 'global.expired' |trans }}{{ deal.dateExpiration | date('d-m-Y')}} </s></div>
                                    {% else %}
                                        <div class="mr-2"><i class="fas fa-hourglass-half mr-2"></i> {{ 'global.expireIn' |trans }}{{ deal.dateExpiration | date('d-m-Y')}} (dans {{ leftDays }} jours)</div>
                                    {% endif %}
                                    <div class="mr-2"><i class="fas fa-street-view mr-2"></i>Spot : {{ deal.localisation }}</div>
                                    <span class="d-flex justify-content-end">{{ deal.categorie.nom }}</span>
                                </div>
                                <h5>{{ deal.titre }}</h5>
                                <div class="mt-1 mb-1 spec-1"><span>{{ deal.description }}</span></div>
                                <div class="d-flex flex-row justify-content-between card-footer mt-3">
                                    <small><i class="fas fa-user-circle lr-3 text-muted mr-2"></i>{{ deal.user.username }}</small>
                                    <small class="text-muted"><i class="fas fa-calendar-minus mr-2 "></i>{{ 'global.upload.date' |trans }} {{ deal.dateDebut | date('d-m-Y')}}</small>
                                </div>
                            </div>
                            <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                                <div class="price d-flex flex-row align-items-center">
                                    <h4 class="mr-1">{{ deal.prixPromo }} €</h4><s>{{ deal.prixOrigine }} €</s>
                                </div>
                                <h6 class="text-success">{{ 'global.delivered.price' |trans }}: {{ deal.livraison }}€</h6>
                                <div class="profil-btn-contain d-flex flex-column mt-4">
                                    <a class="btn btn-outline-primary btn-sm mt-2 " href="{{  deal.url }}">{{ 'global.deal.link.btn' |trans }}<i class="fas fa-bullseye ml-2"></i></a>
                                    <a class="btn btn-danger btn-sm mt-2 " href="{{  path('deal_delete',{'id':deal.id}) }}">{{ 'global.delete.btn' |trans }}<i class="fas fa-trash-alt ml-2"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="/js/index-jquery.js"></script>
    <script type="text/javascript">
        $(function (){
            //FiltersDeals correspond a l'affichage des deals en cours|tous|expiré
            var $FiltersDeals = $("#FiltersDeals");

            $FiltersDeals.find("button").off("click").on("click", function (){
                var that = $(this),
                    type = that.data("type");
                if(type === "tous"){
                    $(".deal").removeClass("d-none");
                }else if(type === "en_cours"){
                    $(".deal").removeClass("d-none");
                    $(".deal.expired").addClass("d-none");
                }else if(type === "expire"){
                    $(".deal").removeClass("d-none");
                    $(".deal:not(.expired)").addClass("d-none");
                }
            })
        })
    </script>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
    </style>
{% endblock %}